server:
  port: 9002

spring:
  application:
    name: ENTREPOT-SERVICE
  zipkin:
    base-url: http://127.0.0.1:9411/
  datasource:
    url: jdbc:h2:mem:entrepot
    username: sa
    password:
    driverClassName: org.h2.Driver
    datesource:
      url: jdbc:h2:file:/data/entrepots
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

