server:
  port: 9001
spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:h2:mem:boutique
    username: sa
    password:
    driverClassName: org.h2.Driver
    datesource:
      url: jdbc:h2:file:/data/products
  h2:
    console:
      enabled: true
  jpa:
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect

  eureka:
    client:
      register-with-eureka: true
      fetch-registry: true
      service-url:
        defaultZone: http://localhost:8761/eureka/
    instance:
      hostname: localhost
